### ISSUE TITLE
Shodan 💻

### ISSUE THREAD

**Issue by mechamogeo** [msfidelis/Kill-Router-#4]
# Tentando utilizar o shodan!

![Kill-Router-](https://preview.ibb.co/d1uSym/Kill_Router_2_0.png)

@msfidelis teria como me ajudar cara? :stuck_out_tongue_winking_eye: , estou tentando fazer acontecer masss (...)
O [Tutorial](http://www.nanoshots.com.br/2016/06/kill-router-10-brute-force-em-massa-em.html) para mim não tem explicação nem mesmo uma introdução ao primeiro uso :sweat_smile:, pois estou perdido tentando entender ao menos um pouco sobre segurança, mas mesmo assim eu nem consigo entender como esse `.py` funciona, mas queria muito ver o que fazer com ele, expandir as minhas capacidades, após colocar a API do shodan não consegui iniciar nem mesmo em modo local, pesquisei videos e não encontrei nenhum compatível que possa me ajudar.

Espero que não leve isso como ~~um insulto~~ algo ruim e me desculpe se estava tudo na minha cara o tempo todo, mas simplesmente estou triste por nem conseguir fazer funcionar.

## Erro na minha tela
```
[x] INVALID SHODAN API KEY
[!] Create a Account and Generate a new API KEY in https://account.shodan.io/login
```

###### Pss: Uso Mac ksksks

**Comment by msfidelis** [comment]
Fala @geovanipfranca , obrigado por reportar isso. 
Seguinte: Há algumas semanas o Kill Router passou por um [refactor](https://github.com/msfidelis/Kill-Router-/commit/48ef1d037ca96456d5845bcc0e5782a0a4bceb5a). Ainda não tive tempo de atualizar os tutoriais. 

Para adquirir uma API do Shodan, basta se cadastrar no [site](https://account.shodan.io/login) e recuperar uma API Key de desenvolvimento. É bem simples. 

Assim que estiver com sua key em mãos, adicione a mesma no arquivo `.env` na raiz do projeto e tente novamente 💃
